### ISSUE TITLE
How to configure customized log name from stdout with logging agent?

### ISSUE THREAD

**Issue by cindy-peng** [GoogleCloudPlatform/google-fluentd#427]
Hi team,

I am using logging agent for my cloud function logging. For this serverless environment, I first use cloud logging library with [redirectToStd](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fgoogleapis%2Fnodejs-logging-winston%23alternative-way-to-ingest-logs-in-google-cloud-managed-environments) to redirect the logging to stdout stream. Logging agent will then pick up the logs from stdout stream and send it to cloud logging API.

However, I noticed that all the logs emitted to stdout and picked up by logging agent were renamed to projects/***/logs/run.googleapis.com%2Fstdout.

Logname with logging agent (log name renamed to projects/***/logs/run.googleapis.com%2Fstdout): https://screenshot.googleplex.com/77DgGzzjp99g6fe
Logname without logging agent: https://screenshot.googleplex.com/3jaiWVbdaTFSsQU

Is there any way that I can keep my original log name as in the second screenshot when use stdout and logginga agent? Looks like I can set up tags specifically to reconfigure the logname? https://cloud.google.com/logging/docs/agent/logging/configuration

Thanks!

**Comment by igorpeshansky** [comment]
Sadly, there's no way to influence the log name via the input data. There are some alternatives that would give you similar ways of filtering the data, e.g., setting log entry labels via the `logging.googleapis.com/labels` payload field (see [Special fields in structured payloads](https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields)). You could also write to a log file instead of `stdout`, which will record the log file name as the log name (see [Write container logs](https://cloud.google.com/run/docs/logging#container-logs)). Hope this helps…
